# https://ls-lint.org/
ls:
  source:
    .css: snake_case
    .scss: snake_case
    .html: kebab-case
    .js: kebab-case
    .ts: kebab-case
    .jsx: PascalCase
    .tsx: PascalCase
    .svelte: PascalCase
    .vue: PascalCase

ignore:
  - .cache
  - .git
  - .husky
  - .vscode
  - dist
  - node_modules
